import type { FormSectionConfig } from "../types";

/** Sidebar item: section id, label, and static required-unfilled count */
export interface EditorSidebarConfig {
  id: string;
  label: string;
  requiredCount: number;
}

/** Sidebar sections in display order. Required counts are static placeholders. */
export const editorSidebarSections: EditorSidebarConfig[] = [
  { id: "section-flex-listings", label: "Flex Listings", requiredCount: 1 },
  { id: "section-listing", label: "Listing", requiredCount: 9 },
  { id: "section-general", label: "General", requiredCount: 2 },
  { id: "section-additional", label: "Additional", requiredCount: 1 },
  { id: "section-rooms", label: "Rooms", requiredCount: 0 },
  {
    id: "section-documents-utilities",
    label: "Documents & Utilities",
    requiredCount: 2,
  },
  { id: "section-green-energy", label: "Green Energy", requiredCount: 0 },
  { id: "section-financial", label: "Financial", requiredCount: 4 },
  { id: "section-showing", label: "Showing", requiredCount: 5 },
  { id: "section-agent-office", label: "Agent / Office", requiredCount: 0 },
  {
    id: "section-remarks-tours-internet",
    label: "Remarks / Tours / Internet",
    requiredCount: 3,
  },
];

/**
 * MLS form section definitions. Supports flat fields or subsections.
 * Structure is automation-friendly; add/edit fields here.
 */
export const propertyFormSections: FormSectionConfig[] = [
  // --- Flex Listings (top section, Yes/No toggle buttons) ---
  {
    id: "section-flex-listings",
    title: "Flex Listings",
    description:
      'Select "Yes" to create a Flex Listing, which will highlight the required fields needed to publish a Flex Listing (a Flex Listing will not reach all Internet display options). Select "No" to input a full, Active listing that has maximum Internet distribution and marketing reach.',
    fields: [
      {
        type: "yesno",
        name: "flex_listing_yn",
        id: "field-flex-listing-yn",
        label: "Flex Listing",
        required: true,
        options: ["Yes", "No"],
      },
    ],
  },
  // --- Listing (subsections: Listing Information, School Information) ---
  {
    id: "section-listing",
    title: "Listing",
    subsections: [
      {
        id: "subsection-listing-information",
        title: "Listing Information",
        fields: [
          {
            type: "select",
            name: "listing_agreement",
            id: "field-listing-agreement",
            label: "Listing Agreement",
            required: true,
            allowEmpty: true,
            options: [
              { value: "exclusive_right", label: "Exclusive Right to Sell" },
              { value: "exclusive_agency", label: "Exclusive Agency" },
              { value: "open_listing", label: "Open Listing" },
            ],
          },
          {
            type: "select",
            name: "listing_service",
            id: "field-listing-service",
            label: "Listing Service",
            required: true,
            allowEmpty: true,
            options: [
              { value: "full_service", label: "Full Service" },
              { value: "limited_service", label: "Limited Service" },
            ],
          },
          {
            type: "number",
            name: "listing_price",
            id: "field-listing-price",
            label: "Listing Price",
            required: true,
            min: 0,
          },
          {
            type: "date",
            name: "expiration_date",
            id: "field-expiration-date",
            label: "Expiration Date",
            required: true,
          },
          {
            type: "date",
            name: "auction_date",
            id: "field-auction-date",
            label: "Auction Date",
          },
          {
            type: "multiselect",
            name: "special_listing_conditions",
            id: "field-special-listing-conditions",
            label: "Special Listing Condition",
            required: true,
            maxSelections: 10,
            options: [
              { value: "none", label: "None" },
              { value: "probate", label: "Probate" },
              { value: "foreclosure", label: "Foreclosure" },
              { value: "short_sale", label: "Short Sale" },
            ],
          },
          {
            type: "select",
            name: "listing_agreement_document",
            id: "field-listing-agreement-document",
            label: "Listing Agreement Document",
            required: true,
            allowEmpty: true,
            options: [
              { value: "txr", label: "TXR" },
              { value: "actris", label: "ACTRIS" },
              { value: "other", label: "Other" },
            ],
          },

          {
            type: "text",
            name: "street_number",
            id: "field-street-number",
            label: "Street #",
            required: true,
          },
          {
            type: "text",
            name: "street_dir_prefix",
            id: "field-street-dir-prefix",
            label: "Street Dir Prefix",
          },
          {
            type: "text",
            name: "street_name",
            id: "field-street-name",
            label: "Street Name",
            required: true,
          },
          {
            type: "text",
            name: "street_suffix",
            id: "field-street-suffix",
            label: "Street Type / Suffix",
            required: true,
          },
          {
            type: "text",
            name: "street_dir_suffix",
            id: "field-street-dir-suffix",
            label: "Street Dir Suffix",
          },
          { type: "text", name: "unit", id: "field-unit", label: "Unit" },

          {
            type: "text",
            name: "county",
            id: "field-county",
            label: "County",
            required: true,
          },
          {
            type: "text",
            name: "city",
            id: "field-city",
            label: "City",
            required: true,
          },
          {
            type: "text",
            name: "state",
            id: "field-state",
            label: "State",
            required: true,
          },
          {
            type: "text",
            name: "out_of_state_county",
            id: "field-out-of-state-county",
            label: "Out of State County",
          },
          {
            type: "text",
            name: "out_of_state_city",
            id: "field-out-of-state-city",
            label: "Out of State City",
          },
          {
            type: "text",
            name: "country",
            id: "field-country",
            label: "Country",
            required: true,
          },

          {
            type: "text",
            name: "zipcode",
            id: "field-zipcode",
            label: "Zip Code",
            required: true,
          },
          {
            type: "text",
            name: "plus_four",
            id: "field-plus-four",
            label: "Plus 4",
          },

          {
            type: "text",
            name: "subdivision",
            id: "field-subdivision",
            label: "Subdivision",
            required: true,
          },
          {
            type: "textarea",
            name: "tax_legal_description",
            id: "field-tax-legal-description",
            label: "Tax Legal Description",
            required: true,
            rows: 3,
            maxLength: 250,
          },
          {
            type: "text",
            name: "tax_lot",
            id: "field-tax-lot",
            label: "Tax Lot",
            required: true,
          },
          {
            type: "text",
            name: "parcel_id",
            id: "field-parcel-id",
            label: "Parcel ID No.",
            required: true,
          },

          {
            type: "yesno",
            name: "additional_parcels",
            id: "field-additional-parcels",
            label: "Additional Parcels",
            options: ["Yes", "No"],
          },
          {
            type: "textarea",
            name: "additional_parcels_description",
            id: "field-additional-parcels-description",
            label: "Additional Parcels Description",
            rows: 2,
          },

          {
            type: "text",
            name: "mls_area",
            id: "field-mls-area",
            label: "MLS Area",
            required: true,
          },

          {
            type: "select",
            name: "fema_flood_plain",
            id: "field-fema-flood-plain",
            label: "FEMA Flood Plain",
            required: true,
            allowEmpty: true,
            options: [
              { value: "x", label: "Zone X" },
              { value: "ae", label: "Zone AE" },
              { value: "ve", label: "Zone VE" },
              { value: "none", label: "None" },
            ],
          },
          {
            type: "yesno",
            name: "etj",
            id: "field-etj",
            label: "ETJ",
            options: ["Yes", "No"],
          },

          {
            type: "map_placeholder",
            name: "map",
            id: "field-map",
            label: "Map",
          },
          {
            type: "text",
            name: "longitude",
            id: "field-longitude",
            label: "Longitude",
            required: true,
          },
          {
            type: "text",
            name: "latitude",
            id: "field-latitude",
            label: "Latitude",
            required: true,
          },
        ],
      },

      {
        id: "subsection-school-information",
        title: "School Information",
        fields: [
          {
            type: "text",
            name: "school_district",
            id: "field-school-district",
            label: "School District",
            required: true,
          },
          {
            type: "text",
            name: "out_of_state_school_district",
            id: "field-out-of-state-school-district",
            label: "Out of State School District",
          },
          {
            type: "text",
            name: "elementary_school",
            id: "field-elementary-school",
            label: "Elementary",
            required: true,
          },
          {
            type: "text",
            name: "elementary_other",
            id: "field-elementary-other",
            label: "Elementary Other",
          },
          {
            type: "text",
            name: "middle_school",
            id: "field-middle-school",
            label: "Middle / Junior",
            required: true,
          },
          {
            type: "text",
            name: "middle_other",
            id: "field-middle-other",
            label: "Middle / Junior Other",
          },
          {
            type: "text",
            name: "high_school",
            id: "field-high-school",
            label: "High School",
            required: true,
          },
          {
            type: "text",
            name: "high_school_other",
            id: "field-high-school-other",
            label: "High School Other",
          },
        ],
      },
    ],
    fields: [],
  },
  // --- General ---
  {
    id: "section-general",
    title: "General",
    description: "Property characteristics and physical details.",
    fields: [
      {
        type: "select",
        name: "property_sub_type",
        id: "field-property-sub-type",
        label: "Property Sub Type",
        required: true,
        allowEmpty: true,
        options: [
          { value: "single_family", label: "Single Family Residence" },
          { value: "condo", label: "Condominium" },
          { value: "townhouse", label: "Townhouse" },
          { value: "duplex", label: "Duplex" },
          { value: "manufactured", label: "Manufactured Home" },
        ],
      },
      {
        type: "select",
        name: "ownership_type",
        id: "field-ownership-type",
        label: "Ownership Type",
        required: true,
        allowEmpty: true,
        options: [
          { value: "fee_simple", label: "Fee Simple" },
          { value: "leasehold", label: "Leasehold" },
          { value: "condo", label: "Condominium" },
        ],
      },
      {
        type: "number",
        name: "levels",
        id: "field-levels",
        label: "Levels",
        required: true,
        min: 0,
      },
      {
        type: "text",
        name: "also_listed_as",
        id: "field-also-listed-as",
        label: "Also Listed As (Enter MLS#)",
      },
      {
        type: "number",
        name: "main_level_bedrooms",
        id: "field-main-level-bedrooms",
        label: "# Main Level Bedrooms",
        required: true,
        min: 0,
      },
      {
        type: "number",
        name: "other_level_bedrooms",
        id: "field-other-level-bedrooms",
        label: "# Other Level Beds",
        min: 0,
      },
      {
        type: "number",
        name: "year_built",
        id: "field-year-built",
        label: "Year Built",
        required: true,
        min: 1700,
        max: new Date().getFullYear(),
      },
      {
        type: "select",
        name: "year_built_source",
        id: "field-year-built-source",
        label: "Year Built Source",
        required: true,
        allowEmpty: true,
        options: [
          { value: "appraisal", label: "Appraisal District" },
          { value: "builder", label: "Builder" },
          { value: "owner", label: "Owner" },
          { value: "public_record", label: "Public Record" },
        ],
      },
      {
        type: "number",
        name: "bathrooms_full",
        id: "field-bathrooms-full",
        label: "Bathrooms Full",
        required: true,
        min: 0,
      },
      {
        type: "number",
        name: "bathrooms_half",
        id: "field-bathrooms-half",
        label: "Bathrooms Half",
        required: true,
        min: 0,
      },
      {
        type: "number",
        name: "living_rooms",
        id: "field-living-rooms",
        label: "# Living",
        required: true,
        min: 0,
      },
      {
        type: "number",
        name: "dining_rooms",
        id: "field-dining-rooms",
        label: "# Dining",
        required: true,
        min: 0,
      },
      {
        type: "number",
        name: "living_area",
        id: "field-living-area",
        label: "Living Area",
        required: true,
        min: 0,
      },
      {
        type: "select",
        name: "living_area_source",
        id: "field-living-area-source",
        label: "Living Area Source",
        required: true,
        allowEmpty: true,
        options: [
          { value: "appraisal", label: "Appraisal District" },
          { value: "builder", label: "Builder" },
          { value: "owner", label: "Owner" },
        ],
      },
      {
        type: "number",
        name: "garage_spaces",
        id: "field-garage-spaces",
        label: "# Garage Spaces",
        required: true,
        min: 0,
      },
      {
        type: "number",
        name: "parking_total",
        id: "field-parking-total",
        label: "Parking Total",
        required: true,
        min: 0,
      },
      {
        type: "select",
        name: "direction_faces",
        id: "field-direction-faces",
        label: "Direction Faces",
        allowEmpty: true,
        options: [
          { value: "north", label: "North" },
          { value: "south", label: "South" },
          { value: "east", label: "East" },
          { value: "west", label: "West" },
          { value: "northeast", label: "Northeast" },
          { value: "northwest", label: "Northwest" },
        ],
      },
      {
        type: "number",
        name: "lot_size_acres",
        id: "field-lot-size-acres",
        label: "Lot Size Acres",
        required: true,
        min: 0,
      },
      {
        type: "text",
        name: "lot_dimensions",
        id: "field-lot-dimensions",
        label: "Lot Dimensions (Frontage x Depth)",
      },
      {
        type: "multiselect",
        name: "property_conditions",
        id: "field-property-conditions",
        label: "Property Conditions",
        required: true,
        maxSelections: 4,
        options: [
          { value: "new_construction", label: "New Construction" },
          { value: "resale", label: "Resale" },
          { value: "under_construction", label: "Under Construction" },
          { value: "fixer", label: "Fixer" },
        ],
      },
      {
        type: "text",
        name: "builder_name",
        id: "field-builder-name",
        label: "Builder Name",
      },
      {
        type: "multiselect",
        name: "unit_style",
        id: "field-unit-style",
        label: "Unit Style",
        maxSelections: 5,
        options: [
          { value: "single_level", label: "Single Level" },
          { value: "multi_level", label: "Multi Level" },
          { value: "end_unit", label: "End Unit" },
          { value: "interior_unit", label: "Interior Unit" },
        ],
      },
      {
        type: "multiselect",
        name: "view",
        id: "field-view",
        label: "View",
        maxSelections: 6,
        options: [
          { value: "city", label: "City" },
          { value: "water", label: "Water" },
          { value: "park", label: "Park" },
          { value: "mountain", label: "Mountain" },
        ],
      },
      {
        type: "multiselect",
        name: "flooring",
        id: "field-flooring",
        label: "Flooring",
        required: true,
        maxSelections: 36,
        options: [
          { value: "tile", label: "Tile" },
          { value: "wood", label: "Wood" },
          { value: "carpet", label: "Carpet" },
          { value: "laminate", label: "Laminate" },
          { value: "vinyl", label: "Vinyl" },
        ],
      },
      {
        type: "multiselect",
        name: "construction_materials",
        id: "field-construction-materials",
        label: "Construction Materials",
        maxSelections: 55,
        options: [
          { value: "brick", label: "Brick" },
          { value: "frame", label: "Frame" },
          { value: "stone", label: "Stone" },
          { value: "stucco", label: "Stucco" },
        ],
      },
      {
        type: "text",
        name: "distance_to_water_access",
        id: "field-distance-to-water-access",
        label: "Distance to Water Access",
      },
      {
        type: "multiselect",
        name: "waterfront_features",
        id: "field-waterfront-features",
        label: "Waterfront Features",
        required: true,
        maxSelections: 12,
        options: [
          { value: "lake", label: "Lake" },
          { value: "river", label: "River" },
          { value: "canal", label: "Canal" },
        ],
      },
      {
        type: "text",
        name: "water_body_name",
        id: "field-water-body-name",
        label: "Water Body Name",
      },
      {
        type: "multiselect",
        name: "parking_features",
        id: "field-parking-features",
        label: "Parking Features",
        required: true,
        maxSelections: 75,
        options: [
          { value: "garage", label: "Garage" },
          { value: "carport", label: "Carport" },
          { value: "driveway", label: "Driveway" },
        ],
      },
      {
        type: "multiselect",
        name: "restrictions",
        id: "field-restrictions",
        label: "Restrictions",
        required: true,
        maxSelections: 15,
        options: [
          { value: "hoa", label: "HOA" },
          { value: "historic", label: "Historic District" },
          { value: "zoning", label: "Zoning" },
        ],
      },
      {
        type: "multiselect",
        name: "foundation_details",
        id: "field-foundation-details",
        label: "Foundation Details",
        required: true,
        maxSelections: 13,
        options: [
          { value: "slab", label: "Slab" },
          { value: "pier_beam", label: "Pier & Beam" },
          { value: "basement", label: "Basement" },
        ],
      },
      {
        type: "multiselect",
        name: "roof",
        id: "field-roof",
        label: "Roof",
        required: true,
        maxSelections: 10,
        options: [
          { value: "composition", label: "Composition" },
          { value: "metal", label: "Metal" },
          { value: "tile", label: "Tile" },
        ],
      },
      {
        type: "multiselect",
        name: "lot_features",
        id: "field-lot-features",
        label: "Lot Features",
        required: true,
        maxSelections: 66,
        options: [
          { value: "corner_lot", label: "Corner Lot" },
          { value: "culdesac", label: "Cul-de-sac" },
          { value: "landscaped", label: "Landscaped" },
        ],
      },
    ],
  },

  // --- Additional ---
  {
    id: "section-additional",
    title: "Additional",
    description: "Interior, exterior, amenities, and community features.",
    fields: [
      {
        type: "multiselect",
        name: "interior_features",
        id: "field-interior-features",
        label: "Interior Features",
        required: true,
        maxSelections: 61,
        options: [
          { value: "high_ceiling", label: "High Ceilings" },
          { value: "open_floorplan", label: "Open Floorplan" },
          { value: "walk_in_closets", label: "Walk-In Closets" },
        ],
      },
      {
        type: "multiselect",
        name: "patio_porch_features",
        id: "field-patio-porch-features",
        label: "Patio and Porch Features",
        required: true,
        maxSelections: 20,
        options: [
          { value: "covered_patio", label: "Covered Patio" },
          { value: "deck", label: "Deck" },
          { value: "screened_porch", label: "Screened Porch" },
        ],
      },
      {
        type: "number",
        name: "fireplaces",
        id: "field-fireplaces",
        label: "# Fireplaces",
        required: true,
        min: 0,
      },
      {
        type: "multiselect",
        name: "exterior_features",
        id: "field-exterior-features",
        label: "Exterior Features",
        required: true,
        maxSelections: 41,
        options: [
          { value: "balcony", label: "Balcony" },
          { value: "rain_gutters", label: "Rain Gutters" },
          { value: "private_yard", label: "Private Yard" },
        ],
      },
      {
        type: "multiselect",
        name: "accessibility_features",
        id: "field-accessibility-features",
        label: "Accessibility Features",
        required: true,
        maxSelections: 37,
        options: [
          { value: "wheelchair_access", label: "Wheelchair Access" },
          { value: "no_steps", label: "No Steps" },
          { value: "wide_doorways", label: "Wide Doorways" },
        ],
      },
      {
        type: "multiselect",
        name: "horse_amenities",
        id: "field-horse-amenities",
        label: "Horse Amenities",
        required: true,
        maxSelections: 18,
        options: [
          { value: "stable", label: "Stable" },
          { value: "arena", label: "Riding Arena" },
          { value: "corral", label: "Corral" },
        ],
      },
      {
        type: "multiselect",
        name: "other_structures",
        id: "field-other-structures",
        label: "Other Structures",
        required: true,
        maxSelections: 20,
        options: [
          { value: "shed", label: "Shed" },
          { value: "workshop", label: "Workshop" },
          { value: "guest_house", label: "Guest House" },
        ],
      },
      {
        type: "multiselect",
        name: "appliances",
        id: "field-appliances",
        label: "Appliances",
        required: true,
        maxSelections: 75,
        options: [
          { value: "dishwasher", label: "Dishwasher" },
          { value: "refrigerator", label: "Refrigerator" },
          { value: "microwave", label: "Microwave" },
        ],
      },
      {
        type: "multiselect",
        name: "pool_features",
        id: "field-pool-features",
        label: "Pool Features",
        required: true,
        maxSelections: 32,
        options: [
          { value: "in_ground", label: "In Ground" },
          { value: "above_ground", label: "Above Ground" },
          { value: "heated", label: "Heated" },
        ],
      },
      {
        type: "multiselect",
        name: "guest_accommodations",
        id: "field-guest-accommodations",
        label: "Guest Accommodations",
        required: true,
        maxSelections: 12,
        options: [
          { value: "guest_suite", label: "Guest Suite" },
          { value: "separate_entrance", label: "Separate Entrance" },
        ],
      },
      {
        type: "multiselect",
        name: "window_features",
        id: "field-window-features",
        label: "Window Features",
        required: true,
        maxSelections: 25,
        options: [
          { value: "double_pane", label: "Double Pane Windows" },
          { value: "bay_window", label: "Bay Window" },
        ],
      },
      {
        type: "multiselect",
        name: "security_features",
        id: "field-security-features",
        label: "Security Features",
        required: true,
        maxSelections: 20,
        options: [
          { value: "security_system", label: "Security System" },
          { value: "gated", label: "Gated" },
          { value: "smoke_detectors", label: "Smoke Detectors" },
        ],
      },
      {
        type: "multiselect",
        name: "laundry_location",
        id: "field-laundry-location",
        label: "Laundry Location",
        required: true,
        maxSelections: 5,
        options: [
          { value: "inside", label: "Inside" },
          { value: "garage", label: "Garage" },
          { value: "utility_room", label: "Utility Room" },
        ],
      },
      {
        type: "multiselect",
        name: "spa_features",
        id: "field-spa-features",
        label: "Spa Features",
        maxSelections: 10,
        options: [
          { value: "hot_tub", label: "Hot Tub" },
          { value: "spa", label: "Spa" },
        ],
      },
      {
        type: "multiselect",
        name: "fencing",
        id: "field-fencing",
        label: "Fencing",
        required: true,
        maxSelections: 29,
        options: [
          { value: "wood", label: "Wood" },
          { value: "iron", label: "Iron" },
          { value: "chain_link", label: "Chain Link" },
        ],
      },
      {
        type: "number",
        name: "guest_full_baths",
        id: "field-guest-full-baths",
        label: "# Guest Full Baths",
        min: 0,
      },
      {
        type: "number",
        name: "guest_half_baths",
        id: "field-guest-half-baths",
        label: "# Guest Half Baths",
        min: 0,
      },
      {
        type: "text",
        name: "distance_ut_shuttle",
        id: "field-distance-ut-shuttle",
        label: "Distance to UT Shuttles",
      },
      {
        type: "text",
        name: "distance_metro",
        id: "field-distance-metro",
        label: "Distance to Metro",
      },
      {
        type: "text",
        name: "distance_light_rail",
        id: "field-distance-light-rail",
        label: "Distance to Light Rail",
      },
      {
        type: "multiselect",
        name: "community_features",
        id: "field-community-features",
        label: "Community Features",
        required: true,
        maxSelections: 78,
        options: [
          { value: "clubhouse", label: "Clubhouse" },
          { value: "playground", label: "Playground" },
          { value: "fitness_center", label: "Fitness Center" },
        ],
      },
      {
        type: "text",
        name: "community_website",
        id: "field-community-website",
        label: "Community Website",
      },
    ],
  },
  // --- Rooms ---
  {
    id: "section-rooms",
    title: "Rooms",
    fields: [
      {
        type: "number",
        name: "bedrooms",
        id: "field-bedrooms",
        label: "Bedrooms",
        min: 0,
        max: 99,
      },
      {
        type: "number",
        name: "bathrooms",
        id: "field-bathrooms",
        label: "Bathrooms",
        min: 0,
        max: 99,
        step: 0.5,
      },
    ],
  },
  // --- Documents & Utilities ---
  {
    id: "section-documents-utilities",
    title: "Documents & Utilities",
    description: "Disclosure documents and utility information.",
    subsections: [
      {
        id: "subsection-documents",
        title: "Documents",
        fields: [
          {
            type: "multiselect",
            name: "disclosures",
            id: "field-disclosures",
            label: "Disclosures",
            required: true,
            maxSelections: 10,
            options: [
              { value: "seller_disclosure", label: "Seller Disclosure" },
              { value: "lead_paint", label: "Lead-Based Paint Disclosure" },
              { value: "hoa_docs", label: "HOA Documents" },
              { value: "survey", label: "Survey" },
            ],
          },
          {
            type: "multiselect",
            name: "utilities",
            id: "field-utilities",
            label: "Utilities",
            required: true,
            maxSelections: 15,
            options: [
              { value: "electricity", label: "Electricity" },
              { value: "natural_gas", label: "Natural Gas" },
              { value: "water", label: "Water" },
              { value: "sewer", label: "Sewer" },
            ],
          },
          {
            type: "multiselect",
            name: "documents_available",
            id: "field-documents-available",
            label: "Documents Available",
            required: true,
            maxSelections: 10,
            options: [
              { value: "floor_plan", label: "Floor Plan" },
              { value: "survey", label: "Survey" },
              { value: "title_commitment", label: "Title Commitment" },
              { value: "inspection_report", label: "Inspection Report" },
            ],
          },
        ],
      },
      {
        id: "subsection-utilities",
        title: "Utilities",
        fields: [
          {
            type: "multiselect",
            name: "heating",
            id: "field-heating",
            label: "Heating",
            required: true,
            maxSelections: 42,
            options: [
              { value: "central", label: "Central" },
              { value: "electric", label: "Electric" },
              { value: "gas", label: "Gas" },
              { value: "heat_pump", label: "Heat Pump" },
            ],
          },
          {
            type: "multiselect",
            name: "cooling",
            id: "field-cooling",
            label: "Cooling",
            required: true,
            maxSelections: 10,
            options: [
              { value: "central_air", label: "Central Air" },
              { value: "wall_unit", label: "Wall Unit" },
              { value: "window_unit", label: "Window Unit" },
            ],
          },
          {
            type: "yesno",
            name: "groundwater_conservation_district",
            id: "field-groundwater-conservation-district",
            label: "Groundwater Conservation District",
            options: ["Yes", "No"],
          },
          {
            type: "multiselect",
            name: "water_source",
            id: "field-water-source",
            label: "Water Source",
            required: true,
            maxSelections: 5,
            options: [
              { value: "public", label: "Public" },
              { value: "well", label: "Well" },
              { value: "community", label: "Community" },
            ],
          },
          {
            type: "multiselect",
            name: "sewer",
            id: "field-sewer",
            label: "Sewer",
            required: true,
            maxSelections: 10,
            options: [
              { value: "public", label: "Public Sewer" },
              { value: "septic", label: "Septic" },
              { value: "community", label: "Community Sewer" },
            ],
          },
        ],
      },
    ],
    fields: [],
  },
  // --- Green Energy ---
  {
    id: "section-green-energy",
    title: "Green Energy",
    description:
      "Energy efficiency, environmental, and sustainability information.",
    subsections: [
      {
        id: "subsection-energy-environment-sustainability",
        title: "Energy, Environment & Sustainability",
        fields: [
          {
            type: "multiselect",
            name: "green_energy_efficient",
            id: "field-green-energy-efficient",
            label: "Green Energy Efficient",
            required: true,
            maxSelections: 20,
            options: [
              {
                value: "energy_star_appliances",
                label: "Energy Star Appliances",
              },
              { value: "solar_panels", label: "Solar Panels" },
              { value: "high_efficiency_hvac", label: "High Efficiency HVAC" },
              { value: "double_pane_windows", label: "Double Pane Windows" },
            ],
          },
          {
            type: "multiselect",
            name: "green_sustainability",
            id: "field-green-sustainability",
            label: "Green Sustainability",
            required: true,
            maxSelections: 9,
            options: [
              { value: "rainwater_harvesting", label: "Rainwater Harvesting" },
              { value: "recycled_materials", label: "Recycled Materials" },
              { value: "low_flow_fixtures", label: "Low Flow Fixtures" },
              { value: "native_landscaping", label: "Native Landscaping" },
            ],
          },
        ],
      },
    ],
    fields: [],
  },
  // --- Financial ---
  {
    id: "section-financial",
    title: "Financial",
    description: "Financial, tax, association, and title information.",
    fields: [
      {
        type: "yesno",
        name: "financial_information_yn",
        id: "field-financial-information-yn",
        label: "Financial Information",
        options: ["Yes", "No"],
      },
      {
        type: "text",
        name: "associate_name",
        id: "field-associate-name",
        label: "Associate Name",
      },
      {
        type: "text",
        name: "hoa_management_company",
        id: "field-hoa-management-company",
        label: "HOA Management Co",
      },
      {
        type: "number",
        name: "associate_fee",
        id: "field-associate-fee",
        label: "Associate Fee",
        min: 0,
      },
      {
        type: "text",
        name: "association_requirement",
        id: "field-association-requirement",
        label: "Association Requirement",
      },
      {
        type: "select",
        name: "association_fee_frequency",
        id: "field-association-fee-frequency",
        label: "Association Fee Frequency",
        allowEmpty: true,
        options: [
          { value: "monthly", label: "Monthly" },
          { value: "quarterly", label: "Quarterly" },
          { value: "annually", label: "Annually" },
        ],
      },
      {
        type: "number",
        name: "association_transfer_fee",
        id: "field-association-transfer-fee",
        label: "Association Transfer Fee",
        min: 0,
      },
      {
        type: "number",
        name: "special_assessment",
        id: "field-special-assessment",
        label: "Special Assessment",
        min: 0,
      },
      {
        type: "multiselect",
        name: "association_fees_include",
        id: "field-association-fees-include",
        label: "Association Fees Include",
        maxSelections: 20,
        options: [
          { value: "water", label: "Water" },
          { value: "trash", label: "Trash" },
          {
            value: "common_area_maintenance",
            label: "Common Area Maintenance",
          },
          { value: "insurance", label: "Insurance" },
        ],
      },
      {
        type: "multiselect",
        name: "acceptable_financing",
        id: "field-acceptable-financing",
        label: "Acceptable Financing",
        required: true,
        maxSelections: 15,
        options: [
          { value: "cash", label: "Cash" },
          { value: "conventional", label: "Conventional" },
          { value: "fha", label: "FHA" },
          { value: "va", label: "VA" },
        ],
      },
      {
        type: "number",
        name: "estimated_tax",
        id: "field-estimated-tax",
        label: "Estimated Tax",
        required: true,
        min: 0,
      },
      {
        type: "number",
        name: "tax_year",
        id: "field-tax-year",
        label: "Tax Year",
        required: true,
        min: 1900,
        max: new Date().getFullYear(),
      },
      {
        type: "number",
        name: "tax_annual_amount",
        id: "field-tax-annual-amount",
        label: "Tax Annual Amount",
        min: 0,
      },
      {
        type: "number",
        name: "tax_assessed_value",
        id: "field-tax-assessed-value",
        label: "Tax Assessment Value",
        required: true,
        min: 0,
      },
      {
        type: "number",
        name: "tax_rate",
        id: "field-tax-rate",
        label: "Tax Rate",
        required: true,
        min: 0,
        step: 0.0001,
      },
      {
        type: "text",
        name: "title",
        id: "field-title",
        label: "Title",
      },
      {
        type: "text",
        name: "preferred_title_company",
        id: "field-preferred-title-company",
        label: "Preferred Title Company",
      },
      {
        type: "multiselect",
        name: "buyer_incentives",
        id: "field-buyer-incentives",
        label: "Buyer Incentives",
        required: true,
        maxSelections: 6,
        options: [
          { value: "closing_costs", label: "Closing Costs" },
          { value: "rate_buydown", label: "Rate Buydown" },
          { value: "home_warranty", label: "Home Warranty" },
        ],
      },
      {
        type: "multiselect",
        name: "tax_exemptions",
        id: "field-tax-exemptions",
        label: "Tax Exemptions",
        required: true,
        maxSelections: 6,
        options: [
          { value: "homestead", label: "Homestead" },
          { value: "senior", label: "Senior" },
          { value: "disabled_veteran", label: "Disabled Veteran" },
        ],
      },
      {
        type: "multiselect",
        name: "possessions",
        id: "field-possessions",
        label: "Possessions",
        required: true,
        maxSelections: 10,
        options: [
          { value: "closing", label: "At Closing" },
          { value: "funding", label: "At Funding" },
          { value: "leaseback", label: "Leaseback" },
        ],
      },
      {
        type: "yesno",
        name: "seller_contributions",
        id: "field-seller-contributions",
        label: "Seller Contributions",
        options: ["Yes", "No"],
      },
      {
        type: "yesno",
        name: "intermediary",
        id: "field-intermediary",
        label: "Intermediary",
        options: ["Yes", "No"],
      },
    ],
  },
  // --- Showing ---
  {
    id: "section-showing",
    title: "Showing",
    description: "Instructions and access information for showings.",
    subsections: [
      {
        id: "subsection-showing-information",
        title: "Showing Information",
        fields: [
          {
            type: "select",
            name: "occupant_type",
            id: "field-occupant-type",
            label: "Occupant Type",
            required: true,
            allowEmpty: true,
            options: [
              { value: "owner", label: "Owner" },
              { value: "tenant", label: "Tenant" },
              { value: "vacant", label: "Vacant" },
              { value: "other", label: "Other" },
            ],
          },
          {
            type: "multiselect",
            name: "showing_requirements",
            id: "field-showing-requirements",
            label: "Showing Requirements",
            required: true,
            maxSelections: 25,
            options: [
              { value: "appointment_required", label: "Appointment Required" },
              { value: "call_agent", label: "Call Agent" },
              { value: "call_owner", label: "Call Owner" },
              {
                value: "no_showings_weekends",
                label: "No Showings on Weekends",
              },
            ],
          },
          {
            type: "text",
            name: "owner_name",
            id: "field-owner-name",
            label: "Owner Name",
            required: true,
          },
          {
            type: "text",
            name: "access_code",
            id: "field-access-code",
            label: "Access Code",
          },
          {
            type: "select",
            name: "lockbox_type",
            id: "field-lockbox-type",
            label: "Lockbox Type",
            required: true,
            allowEmpty: true,
            options: [
              { value: "supra", label: "Supra" },
              { value: "combo", label: "Combo" },
              { value: "sentri", label: "SentriLock" },
              { value: "none", label: "None" },
            ],
          },
          {
            type: "text",
            name: "lockbox_serial_number",
            id: "field-lockbox-serial-number",
            label: "Lockbox Serial No.",
          },
          {
            type: "select",
            name: "showing_contact_type",
            id: "field-showing-contact-type",
            label: "Showing Contact Type",
            allowEmpty: true,
            options: [
              { value: "agent", label: "Agent" },
              { value: "owner", label: "Owner" },
              { value: "tenant", label: "Tenant" },
              { value: "other", label: "Other" },
            ],
          },
          {
            type: "text",
            name: "showing_contact_name",
            id: "field-showing-contact-name",
            label: "Showing Contact Name",
          },
          {
            type: "text",
            name: "showing_contact_phone",
            id: "field-showing-contact-phone",
            label: "Showing Contact Phone",
          },
          {
            type: "text",
            name: "showing_service_phone",
            id: "field-showing-service-phone",
            label: "Showing Service Phone",
          },
          {
            type: "select",
            name: "lockbox_location",
            id: "field-lockbox-location",
            label: "Lockbox Location",
            required: true,
            allowEmpty: true,
            options: [
              { value: "front_door", label: "Front Door" },
              { value: "side_door", label: "Side Door" },
              { value: "garage", label: "Garage" },
              { value: "gate", label: "Gate" },
            ],
          },
          {
            type: "textarea",
            name: "showing_instructions",
            id: "field-showing-instructions",
            label: "Showing Instructions",
            rows: 4,
          },
        ],
      },
    ],
    fields: [],
  },
  // --- Agent / Office ---
  {
    id: "section-agent-office",
    title: "Agent / Office",
    description: "Listing and co-listing agent and office information.",
    subsections: [
      {
        id: "subsection-agent-office-information",
        title: "Agent / Office Information",
        fields: [
          {
            type: "text",
            name: "listing_agent",
            id: "field-listing-agent",
            label: "Listing Agent",
            required: true,
          },
          {
            type: "text",
            name: "listing_agent_full_name",
            id: "field-listing-agent-full-name",
            label: "List Agent Full Name",
          },
          {
            type: "text",
            name: "listing_agent_direct_phone",
            id: "field-listing-agent-direct-phone",
            label: "List Agent Direct Phone",
          },
          {
            type: "text",
            name: "listing_agent_email",
            id: "field-listing-agent-email",
            label: "List Agent Email",
          },
          {
            type: "text",
            name: "listing_office_mls_id",
            id: "field-listing-office-mls-id",
            label: "List Office MLS ID",
          },
          {
            type: "text",
            name: "listing_office_name",
            id: "field-listing-office-name",
            label: "List Office Name",
          },
          {
            type: "text",
            name: "listing_oar",
            id: "field-listing-oar",
            label: "List OAR",
          },
          {
            type: "text",
            name: "co_listing_agent",
            id: "field-co-listing-agent",
            label: "Co-List Agent",
          },
          {
            type: "text",
            name: "co_listing_agent_full_name",
            id: "field-co-listing-agent-full-name",
            label: "Co-List Agent Full Name",
          },
          {
            type: "text",
            name: "co_listing_agent_direct_phone",
            id: "field-co-listing-agent-direct-phone",
            label: "Co-List Agent Direct Phone",
          },
          {
            type: "text",
            name: "co_listing_agent_email",
            id: "field-co-listing-agent-email",
            label: "Co-List Agent Email",
          },
          {
            type: "text",
            name: "co_listing_office_mls_id",
            id: "field-co-listing-office-mls-id",
            label: "Co-List Office MLS ID",
          },
          {
            type: "text",
            name: "co_listing_office_name",
            id: "field-co-listing-office-name",
            label: "Co-List Office Name",
          },
          {
            type: "text",
            name: "co_listing_office_phone",
            id: "field-co-listing-office-phone",
            label: "Co-List Office Phone",
          },
        ],
      },
      {
        id: "subsection-attribution-contact",
        title: "Attribution Contact",
        fields: [
          {
            type: "text",
            name: "attribution_contact_info",
            id: "field-attribution-contact-info",
            label: "Attribution Contact Info",
          },
          {
            type: "select",
            name: "office_default_attribution_type",
            id: "field-office-default-attribution-type",
            label: "Office Default Attribution Type",
            allowEmpty: true,
            options: [
              { value: "agent", label: "Agent" },
              { value: "office", label: "Office" },
              { value: "team", label: "Team" },
            ],
          },
          {
            type: "text",
            name: "office_default_attribution_contact",
            id: "field-office-default-attribution-contact",
            label: "Office Default - Attribution Contact",
          },
          {
            type: "yesno",
            name: "listing_override",
            id: "field-listing-override",
            label: "Listing Override",
            options: ["Yes", "No"],
          },
          {
            type: "textarea",
            name: "attribution_contact_override_notice",
            id: "field-attribution-contact-override-notice",
            label: "Attribution Contact Override Notice",
            rows: 3,
          },
        ],
      },
    ],
    fields: [],
  },
  {
    id: "section-remarks-tours-internet",
    title: "Remarks / Tours / Internet",
    description: "Remarks, virtual tours, and internet display settings.",
    subsections: [
      {
        id: "subsection-remarks-information",
        title: "Remarks Information",
        fields: [
          {
            type: "textarea",
            name: "directions",
            id: "field-directions",
            label: "Directions",
            required: true,
            rows: 3,
            placeholder: "Directions to the property only",
          },
        ],
      },
      {
        id: "subsection-private-remarks",
        title: "Private Remarks",
        fields: [
          {
            type: "textarea",
            name: "public_remarks",
            id: "field-public-remarks",
            label: "Public Remarks",
            required: true,
            rows: 6,
            placeholder: "Write description of the property only",
          },
        ],
      },
      {
        id: "subsection-syndication-remarks",
        title: "Syndication Remarks",
        fields: [
          {
            type: "textarea",
            name: "syndication_remarks",
            id: "field-syndication-remarks",
            label: "Syndication Remarks",
            rows: 4,
          },
        ],
      },
      {
        id: "subsection-virtual-tours",
        title: "Virtual Tours",
        fields: [
          {
            type: "text",
            name: "branded_virtual_tour_url",
            id: "field-branded-virtual-tour-url",
            label: "Branded Virtual Tour URL",
          },
          {
            type: "text",
            name: "unbranded_virtual_tour_url",
            id: "field-unbranded-virtual-tour-url",
            label: "Unbranded Virtual Tour URL",
          },
          {
            type: "text",
            name: "branded_video_tour_url",
            id: "field-branded-video-tour-url",
            label: "Branded Video Tour URL",
          },
          {
            type: "text",
            name: "unbranded_video_tour_url",
            id: "field-unbranded-video-tour-url",
            label: "Unbranded Video Tour URL",
          },
          {
            type: "text",
            name: "listing_detailed_url",
            id: "field-listing-detailed-url",
            label: "Listing Detailed URL",
          },
          {
            type: "yesno",
            name: "property_panorama_virtual_tour",
            id: "field-property-panorama-virtual-tour",
            label: "Create a Property Panorama Virtual Tour",
            options: ["Yes", "No"],
          },
        ],
      },
      {
        id: "subsection-internet-display",
        title: "Internet Display",
        fields: [
          {
            type: "yesno",
            name: "internet_entire_listing_display",
            id: "field-internet-entire-listing-display",
            label: "Internet Entire Listing Display",
            required: true,
            options: ["Yes", "No"],
          },
          {
            type: "yesno",
            name: "internet_automated_valuation_display",
            id: "field-internet-automated-valuation-display",
            label: "Internet Automated Valuation Display",
            required: true,
            options: ["Yes", "No"],
          },
          {
            type: "yesno",
            name: "internet_consumer_comment",
            id: "field-internet-consumer-comment",
            label: "Internet Consumer Comment",
            required: true,
            options: ["Yes", "No"],
          },
          {
            type: "yesno",
            name: "internet_address_display",
            id: "field-internet-address-display",
            label: "Internet Address Display",
            required: true,
            options: ["Yes", "No"],
          },
          {
            type: "multiselect",
            name: "listing_will_appear_on",
            id: "field-listing-will-appear-on",
            label: "Listing Will Appear On",
            required: true,
            maxSelections: 8,
            options: [
              { value: "idx", label: "IDX" },
              { value: "mls_site", label: "MLS Site" },
              { value: "broker_site", label: "Broker Website" },
              { value: "third_party", label: "Third-Party Portals" },
            ],
          },
          {
            type: "textarea",
            name: "listing_appear_remarks",
            id: "field-listing-appear-remarks",
            label: "Listing Appear Remarks",
            rows: 3,
          },
        ],
      },
    ],
    fields: [],
  },
];
